### ISSUE TITLE
Can't use it without site @serverless/website

### ISSUE THREAD

**Issue by hugosenari** [serverless-components/aws-s3#10]
There is no way to use it without another component.
It just does nothing. 
:)

Actual:
---------
```yaml
s3:
  component: '@serverless/aws-s3'
  inputs:
    name: my-bucket-name
    dir: ./dist
```

Doesn't nothing when I run `sls`

Expected:
-------------

Upload `./dist` content to `my-bucket-name`
